---
driver:
  name: vagrant
  boot_timeout: 1200
  gui: true
    

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: matthew_ntrepid/win10_base
    transport:
      name: winrm
      password: vagrant
      username: vagrant
    driver_config:
      guest: windows
      communicator: winrm

suites:
  - name: default
    run_list:
      - recipe[cookbook::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
