# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.guest = :windows
  config.vm.communicator = 'winrm'
  config.winrm.username = 'vagrant'
  config.winrm.password = 'vagrant'

  config.vm.boot_timeout = 600
  config.vm.graceful_halt_timeout = 600

  config.vm.box = 'matthew_ntrepid/win10_base'

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 3389, host: 3389
  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: 'winrm', auto_correct: true
  # config.vm.network :private_network, ip: '10.0.15.15', type: 'dhcp'

  config.vm.provider 'virtualbox' do |vb|
    # Customize the name of VM in VirtualBox manager UI:
    vb.name = 'windows10x64_1803_base'
  end
end
